### ISSUE TITLE
Does this compile on XCode 5.1 for you?

### ISSUE THREAD

**Issue by aledalgrande** [system123/ceres-solver-ios#1]
When I download and build the project it complains it cannot find headers "ceres/..." and also some files, like `miniglog.a`, are missing.

**Comment by system123** [comment]
I trust you found the issue. It is likely that library search paths are still set for my machine. miniglog.a can be compiled as per the instructions on the cerer-solver site. I compile that first and place the built file in the project folder. AFAIK ceres now has a compile script for iOS

**Comment by aledalgrande** [comment]
I basically changed all of the files with the new release, then tweaked some of the settings, but mostly kept yours :)

**Comment by system123** [comment]
If you wouldn't mind, could you create a pull request with the new files so that this is up to date again. Thanks

**Comment by aledalgrande** [comment]
It’s a bit messy right now, as I needed to make it work fast, that’s why I didn’t make a pull request. I’ll try to tidy it up.

## 

Alessandro Dal Grande
